### ISSUE TITLE
📦 Issue 1. Инициализация репозитория и окружения

### ISSUE THREAD

**Issue by vlavlamat** [vlavlamat/maple-test#2]
### 📦 Issue 1. Инициализация репозитория и окружения

**Цель:** подготовить базовую структуру проекта, Docker-окружение и запустить Laravel + Vue 3 SPA.

---

#### 🔧 Что нужно сделать:

* [ ] **Создать публичный репозиторий на GitHub**

  * Название, например: `maple-test`
  * Добавить описание: "Онлайн-платформа для подготовки к экзамену по истории Канады (Laravel + Vue 3)"

* [ ] **Инициализировать проект с `README.md`**

  * Добавить краткое описание проекта
  * Указать технологии: Laravel, Vue 3, Docker
  * Указать лицензию (например, `MIT` или временно оставить приватной)

* [ ] **Добавить `.gitignore`**

  * Использовать Laravel шаблон + Docker-специфичные исключения
  * Добавить:

    ```
    /vendor/
    /node_modules/
    /storage/*.key
    .env
    .idea/
    .vscode/
    docker/*.log
    ```

* [ ] **Создать `.env.example`**

  * Скопировать сгенерированный `.env` и обрезать чувствительные данные
  * Пример:

    ```env
    APP_NAME=MapleTest
    APP_ENV=local
    APP_KEY=
    APP_DEBUG=true
    APP_URL=http://localhost

    DB_CONNECTION=pgsql
    DB_HOST=pgsql
    DB_PORT=5432
    DB_DATABASE=maple_test
    DB_USERNAME=maple_user
    DB_PASSWORD=secret

    STRIPE_KEY=
    STRIPE_SECRET=
    ```

* [ ] **Установить Laravel через Docker**

  * Использовать Laravel Sail **или** собственный `docker-compose`
  * Альтернатива:

    ```bash
    composer create-project laravel/laravel .
    ```

* [ ] **Создать и настроить `docker-compose.yml`**

  * Сервисы:

    * `php` (Laravel)
    * `nginx` (порт 80 → localhost)
    * `pgsql` или `mysql`
    * `redis`
  * Пример docker-compose фрагмента:

    ```yaml
    services:
      app:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        volumes:
          - .:/var/www/html
        depends_on:
          - pgsql

      nginx:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./docker/nginx:/etc/nginx/conf.d
          - .:/var/www/html

      pgsql:
        image: postgres:15
        environment:
          POSTGRES_DB: maple_test
          POSTGRES_USER: maple_user
          POSTGRES_PASSWORD: secret

      redis:
        image: redis:alpine
    ```

* [ ] **Подключить Vite + Vue 3 SPA**

  * Установить:

    ```bash
    npm install
    npm install vue@3 vue-router@4 pinia
    ```
  * В `resources/js/app.js` заменить на:

    ```js
    import { createApp } from 'vue'
    import App from './App.vue'

    createApp(App).mount('#app')
    ```
  * Создать `App.vue`, `router/index.js`, `stores/`, `components/`

* [ ] **Убедиться, что Laravel и Vite работают**

  * Запуск:

    ```bash
    php artisan serve
    npm run dev
    ```
  * Проверить доступность по адресу: `http://localhost`

* [ ] **Создать структуру модулей в `app/Modules/*`**

  * Пример:

    ```
    app/
    └── Modules/
        ├── Test/
        ├── Language/
        ├── Payment/
        └── Admin/
    ```

* [ ] **Установить Stripe SDK**

  * Установить пакет:

    ```bash
    composer require stripe/stripe-php
    ```
