### ISSUE TITLE
🐳 Issue 2. Настройка docker-compose.yml и установка Laravel через Composer-контейнер

### ISSUE THREAD

**Issue by vlavlamat** [vlavlamat/maple-test#4]
**Цель:** создать окружение на основе Docker Compose и установить Laravel внутри проекта, используя отдельный контейнер с Composer.

---

#### ✅ Шаги:

* [ ] Создать директорию `docker/` в корне проекта

  * Внутри неё создать подпапки:

    ```
    docker/
    ├── php/
    └── nginx/
    ```

* [ ] Создать `docker-compose.yml` в корне проекта

  * Минимальный рабочий шаблон:

    ```yaml
    version: '3.8'

    services:
      app:
        image: php:8.3-fpm
        container_name: maple_app
        volumes:
          - ./:/var/www/html
        depends_on:
          - pgsql
          - redis

      composer:
        image: composer:latest
        container_name: maple_composer
        volumes:
          - ./:/app
        working_dir: /app
        entrypoint: ["composer"]

      nginx:
        image: nginx:latest
        container_name: maple_nginx
        ports:
          - "80:80"
        volumes:
          - ./:/var/www/html
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - app

      pgsql:
        image: postgres:15
        container_name: maple_pgsql
        environment:
          POSTGRES_DB: maple_test
          POSTGRES_USER: maple_user
          POSTGRES_PASSWORD: secret
        volumes:
          - pgdata:/var/lib/postgresql/data
        ports:
          - "5432:5432"

      redis:
        image: redis:alpine
        container_name: maple_redis
        ports:
          - "6379:6379"

    volumes:
      pgdata:
    ```

* [ ] Создать `default.conf` в `docker/nginx/`

  * Пример конфигурации Nginx:

    ```nginx
    server {
        listen 80;
        index index.php index.html;
        server_name localhost;
        root /var/www/html/public;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
    }
    ```

* [ ] Запустить инфраструктуру:

  ```bash
  docker compose up -d
  ```

* [ ] Установить Laravel с помощью Composer-контейнера:

  ```bash
  docker compose run --rm composer create-project laravel/laravel .
  ```

* [ ] Убедиться, что после установки структура проекта Laravel появилась в корне:

  ```
  ├── app/
  ├── bootstrap/
  ├── config/
  ├── public/
  ├── routes/
  ├── artisan
  ├── composer.json
  ...
  ```

* [ ] Добавить `storage/` и `bootstrap/cache/` в `volumes` (если требуется перезапись прав)

* [ ] Проверить, что Laravel доступен по адресу: [http://localhost/](http://localhost)
